'use strict';

module.exports = {
  CAPABILITIES: {
    DIM: 'dim',
    ONOFF: 'onoff',
    ALL_ON: 'allOn',
    ALL_OFF: 'allOff',
    LIGHT_HUE: 'light_hue',
    LIGHT_MODE: 'light_mode',
    METER_POWER: 'meter_power',
    RESET_METER: 'resetMeter', // deprecated
    CALIBRATION: 'calibration', // deprecated
    POWER_FACTOR: 'powerFactor',
    ALARM_CONTACT: 'alarm_contact', // deprecated
    MEASURE_POWER: 'measure_power',
    POWER_REACTIVE: 'powerReactive',
    MEASURE_VOLTAGE: 'measure_voltage',
    MEASURE_CURRENT: 'measure_current',
    LIGHT_TEMPERATURE: 'light_temperature',
    LIGHT_SATURATION: 'light_saturation',
    METER_POWER_IMPORT: 'meter_power.import',
    METER_POWER_EXPORT: 'meter_power.export',
    TARGET_TEMPERATURE: 'target_temperature',
    POWER_TOTAL_REACTIVE: 'powerTotalReactive',
    POWER_TOTAL_APPARENT: 'powerTotalApparent',
    MEASURE_TEMPERATURE: 'measure_temperature',
    WINDOWCOVERINGS_SET: 'windowcoverings_set',
    CUSTOM_THERMOSTAT_MODE: 'custom_thermostat_mode', // deprecated
    OFF_AUTO_THERMOSTAT_MODE: 'offAutoThermostatMode',
    METER_RESET_MAINTENANCE_ACTION: 'button.reset_meter',
    CALIBRATION_MAINTENANCE_ACTION: 'button.calibration',
    WINDOWCOVERINGS_TILT_SET: 'windowcoverings_tilt_set',
  },
  DEVICE_CLASS_GENERIC: {
    SENSOR_MULTILEVEL: 'GENERIC_TYPE_SENSOR_MULTILEVEL',
    SENSOR_BINARY: 'GENERIC_TYPE_SENSOR_BINARY',
    SWITCH_BINARY: 'GENERIC_TYPE_SWITCH_BINARY',
    SENSOR_NOTIFICATION: 'GENERIC_TYPE_SENSOR_NOTIFICATION',
    SWITCH_MULTILEVEL: 'GENERIC_TYPE_SWITCH_MULTILEVEL',
    THERMOSTAT: 'GENERIC_TYPE_THERMOSTAT',
  },
  COMMAND_CLASSES: {
    METER: 'METER',
    NOTIFICATION: 'NOTIFICATION',
    SENSOR_BINARY: 'SENSOR_BINARY',
    SWITCH_BINARY: 'SWITCH_BINARY',
    SWITCH_COLOR: 'SWITCH_COLOR',
    THERMOSTAT_MODE: 'THERMOSTAT_MODE',
    SWITCH_MULTILEVEL: 'SWITCH_MULTILEVEL',
    SENSOR_MULTILEVEL: 'SENSOR_MULTILEVEL',
    SWITCH_COLOR_REPORT: 'SWITCH_COLOR_REPORT',
    NOTIFICATION_REPORT: 'NOTIFICATION_REPORT',
    THERMOSTAT_SETPOINT: 'THERMOSTAT_SETPOINT',
    SENSOR_BINARY_REPORT: 'SENSOR_BINARY_REPORT',
    SENSOR_MULTILEVEL_REPORT: 'SENSOR_MULTILEVEL_REPORT'
  },
  FLOWS: {
    RESET_METER: 'resetMeter',
    INPUT_ONE_TOGGLED: 'inputOneToggled',
    INPUT_ONE_TURNED_ON: 'inputOneTurnedOn',
    INPUT_ONE_TURNED_OFF: 'inputOneTurnedOff',
    INPUT_TWO_TOGGLED: 'inputTwoToggled',
    INPUT_TWO_TURNED_ON: 'inputTwoTurnedOn',
    INPUT_TWO_TURNED_OFF: 'inputTwoTurnedOff',
    INPUT_THREE_TOGGLED: 'inputThreeToggled',
    INPUT_THREE_TURNED_ON: 'inputThreeTurnedOn',
    INPUT_THREE_TURNED_OFF: 'inputThreeTurnedOff',
    SET_OFF_AUTO_THERMOSTAT_MODE: 'setOffAutoThermostatMode',
    OFF_AUTO_THERMOSTAT_MODE_CHANGED: 'offAutoThermostatModeChanged',
    LEGACY_INPUT_ONE_TURNED_ON: 'I1_on',
    LEGACY_INPUT_ONE_TURNED_OFF: 'I1_off',
    LEGACY_INPUT_TWO_TURNED_ON: 'I2_on',
    LEGACY_INPUT_TWO_TURNED_OFF: 'I2_off',
    LEGACY_INPUT_THREE_TURNED_ON: 'I3_on',
    LEGACY_INPUT_THREE_TURNED_OFF: 'I3_off',
  },
  INPUT_MAP: {
    1: {
      INPUT_ID: 1,
      FLOW_TRIGGERS: {
        ON: 'inputOneTurnedOn',
        OFF: 'inputOneTurnedOff',
        TOGGLE: 'inputOneToggled',
      },
    },
    2: {
      INPUT_ID: 2,
      FLOW_TRIGGERS: {
        ON: 'inputTwoTurnedOn',
        OFF: 'inputTwoTurnedOff',
        TOGGLE: 'inputTwoToggled',
      },
    },
    3: {
      INPUT_ID: 3,
      FLOW_TRIGGERS: {
        ON: 'inputThreeTurnedOn',
        OFF: 'inputThreeTurnedOff',
        TOGGLE: 'inputThreeToggled',
      },
    },
  },
  SETTINGS: {
    ALL_ON: 'allOn',
    ALL_OFF: 'allOff',
    AUTO_OFF: 'autoOff',
    AUTO_OFF_Q1: 'autoOffQ1',
    AUTO_OFF_Q2: 'autoOffQ2',
    ANTIFREEZE: 'antifreeze',
    PID_DEADBAND: 'pidDeadband',
    WORKING_MODE: 'workingMode',
    DIM_DURATION: 'dimDuration',
    ENABLE_INPUT_1: 'enableInput1',
    ENABLE_INPUT_2: 'enableInput2',
    ENABLE_INPUT_3: 'enableInput3',
    RESTORE_STATUS: 'restoreStatus',
    OPERATING_MODE: 'operatingMode',
    SETPOINT_INPUT_2: 'setpointInput2',
    SETPOINT_INPUT_3: 'setpointInput3',
    THERMOSTAT_MODE: 'thermostatMode',
    MINIMUM_DIM_VALUE: 'minimumDimValue',
    MAXIMUM_DIM_VALUE: 'maximumDimValue',
    MOTOR_MOVING_TIME: 'motorMovingTime',
    SLATS_TILTING_TIME: 'slatsTiltingTime',
    ANTIFREEZE_ENABLED: 'antifreezeEnabled',
    FUNCTIONALITY_INPUT_3: 'functionalityInput3',
    POWER_REPORT_DELAY_TIME: 'powerReportDelayTime',
    POWER_REPORTING_INTERVAL: 'powerReportingInterval',
    DIM_DURATION_KEY_PRESSED: 'dimDurationKeyPressed',
    SETPOINT_INPUT_2_ENABLED: 'setpointInput2Enabled',
    SETPOINT_INPUT_3_ENABLED: 'setpointInput3Enabled',
    TOO_LOW_TEMPERATURE_LIMIT: 'tooLowTemperatureLimit',
    TOO_HIGH_TEMPERATURE_LIMIT: 'tooHighTemperatureLimit',
    TEMPERATURE_SENSOR_OFFSET: 'temperatureSensorOffset',
    MOTOR_OPERATION_DETECTION: 'motorOperationDetection',
    TEMPERATURE_HYSTERESIS_ON: 'temperatureHysteresisOn',
    MOTOR_OFF_DELAY_LIMIT_SWITCH: 'motorOffDelayLimitSwitch',
    TEMPERATURE_HYSTERESIS_OFF: 'temperatureHysteresisOff',
    DELAY_BETWEEN_MOTOR_MOVEMENT: 'delayBetweenMotorMovement',
    INVERT_WINDOW_COVERINGS_DIRECTION: 'invertWindowCoveringsDirection',
    TEMPERATURE_HEATING_HYSTERESIS_ON: 'temperatureHeatingHysteresisOn',
    TEMPERATURE_COOLING_HYSTERESIS_ON: 'temperatureCoolingHysteresisOn',
    TEMPERATURE_HEATING_HYSTERESIS_OFF: 'temperatureHeatingHysteresisOff',
    TEMPERATURE_COOLING_HYSTERESIS_OFF: 'temperatureCoolingHysteresisOff',
    MULTI_CHANNEL_REPORTING_CONFIGURED: 'multiChannelReportingConfigured',
    AUTO_SCENE_MODE_TRANSITION_DURATION: 'autoSceneModeTransitionDuration',
    INVERT_WINDOW_COVERINGS_TILT_DIRECTION: 'invertWindowCoveringsTiltDirection',
    TEMPERATURE_SENSOR_REPORTING_THRESHOLD: 'temperatureSensorReportingThreshold',
    AUTO_SCENE_MODE_TRANSITION_DURATION_UNIT: 'autoSceneModeTransitionDurationUnit',
    SIZE: {
      ALL_ON_ALL_OFF: 2,
    },
    INDEX: {
      allOnAALL_ON_ALL_OFFllOff: 10,
    },
  },
};
